version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 & celery -A WebsiteMonitor worker --loglevel=info -P gevent -Q handle_file'
    volumes:
      - .:/app
      - ./config.prod.ini:/code/config.ini
    ports:
      - "8000:8000"
