# Generated by Django 3.2.25 on 2024-03-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20240311_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitemodel',
            name='url',
        ),
    ]
