# Generated by Django 3.2.25 on 2024-03-13 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_auto_20240313_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayTotalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('ip_today', models.IntegerField(blank=True, null=True, verbose_name='当天访问IP数')),
                ('traffic_time', models.DateField(unique=True, verbose_name='流量日期')),
                ('traffic_today', models.BigIntegerField(blank=True, null=True, verbose_name='当天传输数据量')),
                ('visit_today', models.IntegerField(default=0, verbose_name='当天访问量')),
                ('visitor_today', models.IntegerField(default=0, verbose_name='当天访客量')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.websitemodel', verbose_name='站点')),
            ],
            options={
                'verbose_name': '流量信息',
                'verbose_name_plural': '流量信息',
                'db_table': 't_today_total',
            },
        ),
        migrations.CreateModel(
            name='TotalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('ip_total', models.IntegerField(verbose_name='访问IP总数')),
                ('visit_total', models.IntegerField(verbose_name='总访问量')),
                ('data_transfer_total', models.BigIntegerField(verbose_name='总数据传输量')),
                ('visitor_total', models.IntegerField(verbose_name='总访客数')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.websitemodel', verbose_name='站点')),
            ],
            options={
                'verbose_name': '资源信息',
                'verbose_name_plural': '资源信息',
                'db_table': 't_total',
            },
        ),
        migrations.RemoveField(
            model_name='trafficmodel',
            name='website',
        ),
        migrations.DeleteModel(
            name='ResourceModel',
        ),
        migrations.DeleteModel(
            name='TrafficModel',
        ),
    ]
