# Generated by Django 3.2.25 on 2024-03-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_auto_20240313_0318'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('upload_file', models.FileField(upload_to='log', verbose_name='上传文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.websitemodel', verbose_name='站点')),
            ],
            options={
                'verbose_name': '日志文件',
                'verbose_name_plural': '日志文件',
                'db_table': 't_log_file',
            },
        ),
    ]
