# Generated by Django 3.2.25 on 2024-03-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20240313_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitemodel',
            name='data_transfer_total',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='总数据传输量'),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='日期'),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='ip_total',
            field=models.IntegerField(default=0, verbose_name='访问IP总数'),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='nginx_log_format',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nginx日志格式'),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='visit_total',
            field=models.IntegerField(default=0, verbose_name='总访问量'),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='visitor_total',
            field=models.IntegerField(default=0, verbose_name='总访客数'),
        ),
        migrations.DeleteModel(
            name='TotalModel',
        ),
    ]
