# Generated by Django 3.2.25 on 2024-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20240314_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='path',
            field=models.CharField(max_length=1000, verbose_name='访问路径'),
        ),
        migrations.AlterField(
            model_name='websitemodel',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='域名'),
        ),
    ]
