# Generated by Django 3.2.25 on 2024-03-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20240315_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytotalmodel',
            name='traffic_time',
            field=models.DateField(verbose_name='流量日期'),
        ),
    ]
