# Generated by Django 3.2.25 on 2024-03-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_visitmodel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='visit_time',
            field=models.DateTimeField(verbose_name='访问时间'),
        ),
    ]
