# Generated by Django 3.2.25 on 2024-03-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_alter_websitemodel_deploy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='malicious_request',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否恶意请求'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='method',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='status_code',
            field=models.IntegerField(db_index=True, verbose_name='HTTP状态码'),
        ),
    ]
