# Generated by Django 3.2.25 on 2024-03-20 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_auto_20240320_0555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitmodel',
            options={'ordering': ['-visit_time'], 'verbose_name': '访问信息', 'verbose_name_plural': '访问信息'},
        ),
    ]
