# Generated by Django 3.2.25 on 2024-04-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_alter_visitmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitmodel',
            name='HTTP_protocol',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HTTP协议'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='http_x_forwarded_for',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='实际的客户端IP'),
        ),
    ]
