# Generated by Django 3.2.25 on 2024-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_alter_websitemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitemodel',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='域名'),
        ),
    ]
