# Generated by Django 3.2.25 on 2024-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_logfilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfilemodel',
            name='nginx_log_format',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Nginx日志格式'),
        ),
    ]
