# Generated by Django 3.2.25 on 2024-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0030_usersettingsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfilemodel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='处理状态'),
        ),
    ]
