# Generated by Django 3.2.25 on 2024-04-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0031_alter_logfilemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfilemodel',
            name='status',
            field=models.IntegerField(default=0, verbose_name='处理状态'),
        ),
    ]
