# Generated by Django 3.2.25 on 2024-04-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0032_alter_logfilemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfilemodel',
            name='status',
            field=models.IntegerField(default=1, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='logfilemodel',
            name='upload_file',
            field=models.FileField(upload_to='log/', verbose_name='上传文件'),
        ),
    ]
