# Generated by Django 3.2.25 on 2024-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0033_auto_20240411_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('total_visit', models.IntegerField(default=0, verbose_name='总访问量')),
                ('total_ip', models.IntegerField(default=0, verbose_name='总访问IP数')),
                ('google_bot', models.IntegerField(default=0, verbose_name='GoogleBot访问量')),
            ],
            options={
                'verbose_name': '汇总',
                'verbose_name_plural': '汇总',
                'db_table': 't_total',
            },
        ),
    ]
