# Generated by Django 3.2.25 on 2024-04-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0035_totalmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmodel',
            name='visit_date',
            field=models.DateField(db_index=True, default=None, verbose_name='日期'),
        ),
    ]
