# Generated by Django 3.2.25 on 2024-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0036_totalmodel_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalmodel',
            name='total_visit',
        ),
        migrations.AddField(
            model_name='totalmodel',
            name='google_visit',
            field=models.IntegerField(default=0, verbose_name='来自google的总访问量'),
        ),
    ]
