# Generated by Django 3.2.25 on 2024-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0037_auto_20240423_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalmodel',
            name='total_visit',
            field=models.IntegerField(default=0, verbose_name='统计访问量'),
        ),
    ]
