# Generated by Django 3.2.25 on 2024-04-29 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0038_totalmodel_total_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='域名')),
                ('google_referer', models.IntegerField(default=0, verbose_name='来自google的访问量')),
                ('ips', models.IntegerField(default=0, verbose_name='总访问IP数')),
                ('google_bot', models.IntegerField(default=0, verbose_name='GoogleBot访问量')),
                ('visits', models.IntegerField(default=0, verbose_name='统计访问量')),
                ('data_transfers', models.BigIntegerField(blank=True, null=True, verbose_name='数据传输总量')),
                ('visit_date', models.DateField(db_index=True, default=None, verbose_name='日期')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计',
                'db_table': 't_total_day',
            },
        ),
    ]
