# Generated by Django 3.2.25 on 2024-04-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0039_totaldaymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaldaymodel',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='域名'),
        ),
    ]
