# Generated by Django 3.2.25 on 2024-04-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0040_alter_totaldaymodel_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaldaymodel',
            options={'ordering': ['-visit_date'], 'verbose_name': '每日统计', 'verbose_name_plural': '每日统计'},
        ),
    ]
