# Generated by Django 3.2.25 on 2024-04-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0041_alter_totaldaymodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaldaymodel',
            options={'verbose_name': '每日统计', 'verbose_name_plural': '每日统计'},
        ),
    ]
