# Generated by Django 3.2.25 on 2024-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0042_alter_totaldaymodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaldaymodel',
            name='url_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='唯一的url总数'),
        ),
    ]
