# Generated by Django 3.2.25 on 2024-05-09 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitor', '0043_totaldaymodel_url_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('domain', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='域名')),
                ('ip', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='IP')),
                ('ip_count', models.IntegerField(default=0, verbose_name='IP数量')),
                ('google_bot', models.BooleanField(default=False, verbose_name='是否是GoogleBot')),
                ('visit_date', models.DateField(db_index=True, default=None, verbose_name='日期')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日IP统计',
                'verbose_name_plural': '每日IP统计',
                'db_table': 't_ip_day',
            },
        ),
    ]
