# Generated by Django 3.2.25 on 2024-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0044_ipdaymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdaymodel',
            name='google_bot',
        ),
        migrations.AlterField(
            model_name='ipdaymodel',
            name='status',
            field=models.IntegerField(choices=[(0, '其他'), (1, 'googlebot'), (2, '异常')], default=0, verbose_name='状态'),
        ),
    ]
