# Generated by Django 3.2.25 on 2024-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0045_auto_20240509_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipdaymodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='国家'),
        ),
    ]
