# Generated by Django 3.2.25 on 2024-05-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0046_ipdaymodel_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdaymodel',
            old_name='ip_count',
            new_name='count',
        ),
    ]
