# Generated by Django 3.2.25 on 2024-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitmodel',
            name='ip',
        ),
        migrations.AddField(
            model_name='resourcemodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='trafficmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='http_referer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HTTP_REFERER'),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='http_x_forwarded_for',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='实际的客户端IP'),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='malicious_request',
            field=models.BooleanField(default=False, verbose_name='是否恶意请求'),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端IP'),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='request_time',
            field=models.FloatField(blank=True, null=True, verbose_name='请求时间'),
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='websitemodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
