# Generated by Django 3.2.25 on 2024-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_websitemodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='user_agent',
            field=models.CharField(max_length=255, verbose_name='User-Agent'),
        ),
    ]
