# Generated by Django 3.2.25 on 2024-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_visitmodel_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficmodel',
            name='page_view',
        ),
        migrations.RemoveField(
            model_name='trafficmodel',
            name='traffic',
        ),
        migrations.RemoveField(
            model_name='trafficmodel',
            name='unique_visitor',
        ),
        migrations.AddField(
            model_name='trafficmodel',
            name='ip_today',
            field=models.IntegerField(blank=True, null=True, verbose_name='当天访问IP数'),
        ),
        migrations.AddField(
            model_name='trafficmodel',
            name='traffic_today',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='当天传输数据量'),
        ),
        migrations.AddField(
            model_name='trafficmodel',
            name='visit_today',
            field=models.IntegerField(default=0, verbose_name='当天访问量'),
        ),
        migrations.AddField(
            model_name='trafficmodel',
            name='visitor_today',
            field=models.IntegerField(default=0, verbose_name='当天访客量'),
        ),
    ]
