# Generated by Django 3.2.25 on 2024-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_logfilemodel_nginx_log_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitmodel',
            name='http_referer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HTTP_REFERER'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='path',
            field=models.CharField(max_length=255, verbose_name='访问路径'),
        ),
    ]
