# Generated by Django 3.2.25 on 2024-03-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_alter_visitmodel_visit_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitemodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='客户端IP'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='user_agent',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='visit_time',
            field=models.DateTimeField(db_index=True, verbose_name='访问时间'),
        ),
    ]
