# Generated by Django 3.2.25 on 2024-03-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_auto_20240318_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaytotalmodel',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.websitemodel', verbose_name='站点'),
        ),
    ]
